// frontend/src/constants/locations.ts
export const REGIOES_ADMINISTRATIVAS = [
  "Brazlândia",
  "Ceilândia",
  "Taguatinga",
  "Sol Nascente/Pôr do Sol",
  "Samambaia",
  "Plano Piloto",
  "Águas Claras",
  "Arniqueira",
  "Candangolândia",
  "Cruzeiro",
  "Fercal",
  "Gama",
  "Guará",
  "Itapoã",
  "Jardim Botânico",
  "Lago Norte",
  "Lago Sul",
  "Núcleo Bandeirante",
  "Paranoá",
  "Park Way",
  "Planaltina",
  "Recanto das Emas",
  "Riacho Fundo",
  "Riacho Fundo II",
  "Santa Maria",
  "São Sebastião",
  "SCIA/Estrutural",
  "Sia",
  "Sobradinho",
  "Sobradinho II",
  "Sudoeste/Octogonal",
  "Varjão",
  "Vicente Pires"
] as const;