// frontend/src/constants/routes.ts
export const ROUTE_PATHS = {
  LOGIN: '/',
  DASHBOARD: '/dashboard',
  CASES: 'cases',
  CLOSED_CASES: 'cases/closed',
  CASE_DETAIL: 'cases/:id',
  AGENDA: 'agenda',
  TEAM: 'team-overview',
  REPORTS: 'reports',
  USERS: 'users',
  GROUPS: 'groups', // [NOVO]
  NOT_FOUND: '*',
} as const

export const ROUTES = {
  LOGIN: ROUTE_PATHS.LOGIN,
  DASHBOARD: ROUTE_PATHS.DASHBOARD,
  CASES: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.CASES}`,
  CLOSED_CASES: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.CLOSED_CASES}`,
  AGENDA: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.AGENDA}`,
  TEAM_OVERVIEW: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.TEAM}`,
  REPORTS: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.REPORTS}`,
  USERS: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.USERS}`,
  GROUPS: `${ROUTE_PATHS.DASHBOARD}/${ROUTE_PATHS.GROUPS}`, // [NOVO]
  NOT_FOUND: ROUTE_PATHS.NOT_FOUND,
  CASE_DETAIL: (id: string) => `${ROUTE_PATHS.DASHBOARD}/cases/${id}`,
} as const